title: Calculus 1 Formula Sheet 
author: Mustafif Khan
description: This formula sheet will contain all necessary needed
formulas for Calculus 1. These will contain topics with Trig identities, to 
differential properties. All will be included here. 
